// <auto-generated />
using System;
using GameCatalog.API.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace GameCatalog.API.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260916011040_InitDb")]
    partial class InitDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameCatalog.API.Domain.Entities.EstudioEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnoFundacao")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("i_ano_fundacao");

                    b.Property<bool>("Ativo")
                        .HasColumnType("BOOLEAN")
                        .HasColumnName("b_ativo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("s_nome");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR2(60)")
                        .HasColumnName("s_pais");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "Nome" }, "IDX_ESTUDIO_NOME")
                        .IsUnique();

                    b.HasIndex(new[] { "Pais", "AnoFundacao" }, "IDX_ESTUDIO_PAIS_ANO");

                    b.ToTable("tb_estudio");
                });

            modelBuilder.Entity("GameCatalog.API.Domain.Entities.JogoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("d_lancamento");

                    b.Property<int>("EstudioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("i_estudio_id");

                    b.Property<int>("Genero")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("i_genero");

                    b.Property<double>("Nota")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("n_nota");

                    b.Property<double>("Preco")
                        .HasColumnType("BINARY_DOUBLE")
                        .HasColumnName("n_preco");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("s_titulo");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "EstudioId", "DataLancamento" }, "IDX_JOGO_ESTUDIO_DATA");

                    b.HasIndex(new[] { "Genero", "Preco" }, "IDX_JOGO_GENERO_PRECO");

                    b.HasIndex(new[] { "Titulo" }, "IDX_JOGO_TITULO");

                    b.ToTable("tb_jogo");
                });

            modelBuilder.Entity("GameCatalog.API.Domain.Entities.PlataformaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("s_nome");

                    b.HasKey("Id");

                    b.ToTable("tb_plataforma");
                });

            modelBuilder.Entity("JogoEntityPlataformaEntity", b =>
                {
                    b.Property<int>("JogosId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("PlataformasId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("JogosId", "PlataformasId");

                    b.HasIndex("PlataformasId");

                    b.ToTable("tb_jogo_plataforma", (string)null);
                });

            modelBuilder.Entity("GameCatalog.API.Domain.Entities.JogoEntity", b =>
                {
                    b.HasOne("GameCatalog.API.Domain.Entities.EstudioEntity", "Estudio")
                        .WithMany("Jogos")
                        .HasForeignKey("EstudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estudio");
                });

            modelBuilder.Entity("JogoEntityPlataformaEntity", b =>
                {
                    b.HasOne("GameCatalog.API.Domain.Entities.JogoEntity", null)
                        .WithMany()
                        .HasForeignKey("JogosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameCatalog.API.Domain.Entities.PlataformaEntity", null)
                        .WithMany()
                        .HasForeignKey("PlataformasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameCatalog.API.Domain.Entities.EstudioEntity", b =>
                {
                    b.Navigation("Jogos");
                });
#pragma warning restore 612, 618
        }
    }
}
